"""empty message

Revision ID: db24f838d73a
Revises: 
Create Date: 2019-05-27 15:14:42.920826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db24f838d73a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Familias',
    sa.Column('id_familia', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rendaMensal', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_familia')
    )
    op.create_table('Usuarios',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fnome', sa.String(length=45), nullable=False),
    sa.Column('lnome', sa.String(length=45), nullable=False),
    sa.Column('nascimento', sa.Date(), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=45), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.Column('diaReceberSalario', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('login')
    )
    op.create_table('Integrantes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_integrante', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_familia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_familia'], ['Usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_integrante'], ['Familias.id_familia'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_familia'),
    sa.UniqueConstraint('id_integrante')
    )
    op.create_table('Recursos',
    sa.Column('id_recurso', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id_usuario', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Integer(), nullable=True),
    sa.Column('dataPagamento', sa.DateTime(), nullable=True),
    sa.Column('nome', sa.String(length=45), nullable=True),
    sa.Column('dataCancelamento', sa.DateTime(), nullable=True),
    sa.Column('dataAnotacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id_usuario'], ['Usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_recurso')
    )
    op.create_table('Contribuintes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_contribuinte', sa.Integer(), nullable=False),
    sa.Column('dinheiroRecebido', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_contribuinte'], ['Integrantes.id_integrante'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_contribuinte')
    )
    op.create_table('Dependentes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_dependente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_dependente'], ['Integrantes.id_integrante'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_dependente')
    )
    op.create_table('Despesas',
    sa.Column('id_despesa', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_recurso', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_recurso'], ['Recursos.id_recurso'], ),
    sa.PrimaryKeyConstraint('id_despesa')
    )
    op.create_table('Gerenciadores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_gerenciador', sa.Integer(), nullable=False),
    sa.Column('salario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_gerenciador'], ['Integrantes.id_integrante'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Receitas',
    sa.Column('id_receita', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_recurso', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_recurso'], ['Recursos.id_recurso'], ),
    sa.PrimaryKeyConstraint('id_receita')
    )
    op.create_table('AuxiliosDependencias',
    sa.Column('id_auxilio', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_dependente', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=True),
    sa.Column('deferido', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_dependente'], ['Dependentes.id_dependente'], ),
    sa.PrimaryKeyConstraint('id_auxilio')
    )
    op.create_table('DespesasComuns',
    sa.Column('id_despesaComum', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('despesa_id_despesa', sa.Integer(), nullable=False),
    sa.Column('is_constante', sa.Boolean(), nullable=False),
    sa.Column('is_automatica', sa.Boolean(), nullable=False),
    sa.Column('diaMes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['despesa_id_despesa'], ['Despesas.id_despesa'], ),
    sa.PrimaryKeyConstraint('id_despesaComum')
    )
    op.create_table('DespesasEstimadas',
    sa.Column('id_despesaEstimada', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('despesa_id_despesa', sa.Integer(), nullable=False),
    sa.Column('confirmada', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['despesa_id_despesa'], ['Despesas.id_despesa'], ),
    sa.PrimaryKeyConstraint('id_despesaEstimada')
    )
    op.create_table('DespesasIncomuns',
    sa.Column('id_despesaIncomum', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('despesa_id_despesa', sa.Integer(), nullable=False),
    sa.Column('destino', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['despesa_id_despesa'], ['Despesas.id_despesa'], ),
    sa.PrimaryKeyConstraint('id_despesaIncomum')
    )
    op.create_table('DespesasProgramadas',
    sa.Column('id_despesaProgramada', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('despesa_id_despesa', sa.Integer(), nullable=False),
    sa.Column('deferido', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['despesa_id_despesa'], ['Despesas.id_despesa'], ),
    sa.PrimaryKeyConstraint('id_despesaProgramada')
    )
    op.create_table('ReceitasComuns',
    sa.Column('id_receitaComum', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('receita_id_receita', sa.Integer(), nullable=False),
    sa.Column('is_constante', sa.Boolean(), nullable=False),
    sa.Column('is_automatica', sa.Boolean(), nullable=False),
    sa.Column('diaMes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['receita_id_receita'], ['Receitas.id_receita'], ),
    sa.PrimaryKeyConstraint('id_receitaComum')
    )
    op.create_table('ReceitasIncomuns',
    sa.Column('id_receitaIncomum', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('receita_id_receita', sa.Integer(), nullable=False),
    sa.Column('atualizada', sa.Boolean(), nullable=False),
    sa.Column('emissor', sa.String(length=45), nullable=True),
    sa.Column('motivo', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['receita_id_receita'], ['Receitas.id_receita'], ),
    sa.PrimaryKeyConstraint('id_receitaIncomum')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ReceitasIncomuns')
    op.drop_table('ReceitasComuns')
    op.drop_table('DespesasProgramadas')
    op.drop_table('DespesasIncomuns')
    op.drop_table('DespesasEstimadas')
    op.drop_table('DespesasComuns')
    op.drop_table('AuxiliosDependencias')
    op.drop_table('Receitas')
    op.drop_table('Gerenciadores')
    op.drop_table('Despesas')
    op.drop_table('Dependentes')
    op.drop_table('Contribuintes')
    op.drop_table('Recursos')
    op.drop_table('Integrantes')
    op.drop_table('Usuarios')
    op.drop_table('Familias')
    # ### end Alembic commands ###
